# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            Luis Garcia
subtitle:         Developer
description:      This is the personal website of Luis Garcia. Here you can read both technical and non-technical blogs, look at some projects, and get a little more insight about what makes him tick.
keywords:         luis garcia github developer software engineer
language:         "en" # default language of the blog. Language codes: http://www.w3schools.com/tags/ref_language_codes.asp
destination:      docs

#baseurl:         "/docs" # the subpath of your site, e.g. /blog

#url:             "testurl" # the base hostname & protocol for your site. Have a look at robots.txt as well!
                  #populating "url" can append the url to certain hrefs like css and js
permalink:        /blog/:categories/:title
#cover:            /assets/mountain-cover.jpg
disqus_shortname: "jekylldecent"

# Build settings
sass:
    style: compressed
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
include: ['_pages']
exclude: [vendor, "developer-tools"]
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]
  blanklines: true
  startings: [head, body]
